### ISSUE TITLE
Upgrade to 1.9

### ISSUE THREAD

**Issue by monpelaud** [korylprince/hassio-apcupsd#12]
Hi,
I use hassio with Home Assistant 0.95.4 and when I try to updrage APC UPS Daemon v1.8 to 1.9 I get this error message:

19-07-03 11:29:59 INFO (SyncWorker_4) [hassio.docker.interface] Update image korylprince/hassio-apcupsd-armv7:1.8 to korylprince/hassio-apcupsd-armv7:1.9
19-07-03 11:29:59 INFO (SyncWorker_4) [hassio.docker.interface] Pull image korylprince/hassio-apcupsd-armv7 tag 1.9.
19-07-03 11:30:01 ERROR (SyncWorker_4) [hassio.docker.interface] Can't install korylprince/hassio-apcupsd-armv7:1.9 -> 404 Client Error: Not Found ("manifest for korylprince/hassio-apcupsd-armv7:1.9 not found").

Please can You help me ?

Best regards

**Comment by Padre653** [comment]
I'm seeing the same issue.

**Comment by rbray89** [comment]
Seeing the same issue, but for the aarch64 architecture.

**Comment by korylprince** [comment]
There was [an issue](https://github.com/korylprince/hassio-apcupsd/pull/11#issuecomment-507883653) with the hassio base images that left me unable to build and push 1.9.

That was fixed and I've since built and pushed 1.9, so you should be able to update now.
