### ISSUE TITLE
extra key's not working.

### ISSUE THREAD

**Issue by Vorms** [korylprince/hassio-apcupsd#13]
I want to override parameters of apcupsd.
I have this config in configuration.yaml:
```
apcupsd:
 "extra": [
    {"key": "BATTERYLEVEL", "val": 15},
    {"key": "MINUTES", "val": 5}
 ]
```
the error message is:

> Invalid config for [apcupsd]: [extra] is an invalid option for [apcupsd]. Check: apcupsd->apcupsd->extra. (See /config/configuration.yaml, line 111). Please check the docs at 
> https://home-assistant.io/components/apcupsd/

Many thanks for your help

**Comment by korylprince** [comment]
@Vorms 

You're trying to put Hassio add-on configuration in the home assistant configuration.yaml.

Are you running [Hass.io](https://www.home-assistant.io/hassio/)? If so, then you need to [install this add-on](https://github.com/korylprince/hassio-apcupsd#installation) and put that configuration in the add-on configuration (through the Hass.io web interface.)

If you aren't running Hass.io, then this add-on isn't for you and you'll need to install acpupsd yourself.
