### ISSUE TITLE
not getting all sensor values from SRT750I

### ISSUE THREAD

**Issue by matajumotors** [korylprince/hassio-apcupsd#17]
Hi, I just found this addon (v1.9) and installed on my hassio.
APC SRT750I is connected using USB cable from UPS to Raspberry Pi.
Problem I get is that there are many sensors like Line voltage etc showing up as "unknown".
PowerChute does display those correctly when ups connected to a PC.

![image](https://user-images.githubusercontent.com/9872291/73609217-698cdd00-45c3-11ea-9f06-33f84ea9eab1.png)

Have I missed something?

Thanks,
Kaspars

**Comment by korylprince** [comment]
Based on what I'm seeing, apcupsd is at least partially in communication with your UPS. Here's my guess at what the issue could be:

- Misconfiguration of apcupsd (check your config to make sure everything is correct)
- Wrong resources configured (check [this section](https://www.home-assistant.io/integrations/apcupsd/#resources) on configuring resources; maybe your UPS has different names?)
- This seems simple, but maybe you didn't wait long enough for the data to show up?

From your computer run `apcaccess -h <your hass.io IP>`. That should give you what the apcupsd is actually seeing from your UPS. If the data you need is there, it's an issue of miscommunication between Home Assistant and apcupsd. If it's not there, it's an issue of miscommunication between apcupsd and your UPS.

**Comment by matajumotors** [comment]
Here what I can see when connected to the PC:
![image](https://user-images.githubusercontent.com/9872291/73783298-59bff500-478b-11ea-8cd7-1c8b2c0f27cb.png)

and here is what I read from hassio:
![image](https://user-images.githubusercontent.com/9872291/73783528-c0dda980-478b-11ea-8536-608889706b85.png)

So toes this mean that apcupsd installed on hassio is not reading what it should?

**Comment by matajumotors** [comment]
Reading the apcupsd documentation, it seems that to read the "advanced" data I need to use MODBUS over USB or RS232. How I can I achieve this using this ad-on?

I think I find the answer from [the manual](http://www.apcupsd.org/manual/manual.html):
![image](https://user-images.githubusercontent.com/9872291/73792268-d8249300-479b-11ea-965a-a9fb89be780b.png)
So I did sent theese as bellow, but then comms are lost no matter what:
![image](https://user-images.githubusercontent.com/9872291/73792327-f4283480-479b-11ea-93e5-07699633cc55.png)

I found one [thread here](https://forums.unraid.net/topic/50213-anyone-successfully-using-modbus-usb-with-apcupsd/) where same happened and the apsupsd had do be build with the './configure --modbus-usb' flag.

Did I encounter the same thing? What needs to be done to get it working on Hassio?

running apcupsd on PC with modbus config works and  I get all I want:
![image](https://user-images.githubusercontent.com/9872291/73793290-fe4b3280-479d-11ea-815c-ad28cb317c3e.png)

**Comment by korylprince** [comment]
So I think you're on the right track. However, v1.9 includes [apcupsd  3.14.14-r1](https://git.alpinelinux.org/aports/commit/?id=de0c11db7326ef89ead739928ed6d1e6c71b2d64) which has the `--enable-modbus-usb` option enabled already.

I can't see anything you've configured wrongly, so I'm not sure why it works on your PC but not this add-on. I'm afraid I can't think of anything else to try to get it working.

A possible alternative would be to leave apcupsd running on your PC and use the `_net` version of this add-on to connect to your PC.

**Comment by korylprince** [comment]
There haven't been any updates to this issue, so I'm closing it. I suggest anyone having issues with MODBUS check out [this post](https://community.home-assistant.io/t/new-apcupsd-hass-io-add-on/35149/90) which describes what needs to be done to get MODBUS working properly.
