### ISSUE TITLE
APC UPS Daemon (No USB) where and how can I define the UPS IP address

### ISSUE THREAD

**Issue by redskinhu** [korylprince/hassio-apcupsd#19]
Hi

I have an APC SMT750I UPS with UPS Network Management Card 2 (AP9631)
I can reach the UPS from browser / telnet / SNMP. IP address is: 192.168.252

I wanted to use this addon but I don't know where and how can I define the card's IP address in the addon.

I tried to setup in the config:
```
name: APC UPS
cable: ether
type: net
device: 192.168.252
extra: []
```
I tried too:
`device: '192.168.252:user:password'`
and 
`device: '192.168.252:*user*:password'`

But I got the same error every time:

```
Feb 12 22:26:06 a722577e-apcupsd-net syslog.info syslogd started: BusyBox v1.30.1
Feb 12 22:26:06 a722577e-apcupsd-net daemon.notice apcupsd[6]: apcupsd 3.14.14 (31 May 2016) unknown startup succeeded
Feb 12 22:26:06 a722577e-apcupsd-net daemon.info apcupsd[6]: NIS server startup succeeded
Feb 12 22:26:21 a722577e-apcupsd-net daemon.warn apcupsd[6]: Communications with UPS lost.
send-mail: account default not found: no configuration file available
```

The USB version is works fine anyway.

Any idea?

Thanks
T

**Comment by korylprince** [comment]
I've never dealt myself with an APC network UPS. 

I'm not sure if it's a typo, but `192.168.252` is not an IP address. You should have 4 numbers, not 3.

Beyond that, I recommend you read through [this thread](https://forums.unraid.net/topic/57115-apc-ups-with-network-card-help-resolved/) which seems to have a lot of different troubleshooting advice.

A few tidbits:

* `net` is used for connecting to another apcupsd instance. `snmp` is for connecting to SNMP UPSes (which I think yours is)
* The username/password is not necessarily what the web username/password is

Try checking those things, and read through that thread, and if you still can't get it working, come back here.

**Comment by korylprince** [comment]
There haven't been any updates to this issue so I'm closing it.
