### ISSUE TITLE
One UPS for two instances Home Assistanse

### ISSUE THREAD

**Issue by artbrayko** [korylprince/hassio-apcupsd#20]
I have two instances Home Assistans on two Raspberra Pi.
One of them is connected to UPS by usb and configured using your add-on apcupsd.
How to make UPS statuses from one server send to a second server ?
Thank you!

**Comment by korylprince** [comment]
You have two options:

1. You can run the `apcupsd_net` version of the add-on on the second Pi and point it to the IP of the first Pi. I suggest you search through [this thread](https://community.home-assistant.io/t/new-apcupsd-hass-io-add-on/35149) for examples of people doing this sort of setup.
2. You can just not run the add-on on the second Pi, and just point Home Assistant directly to the IP of the first Pi.
