### ISSUE TITLE
Can you please help me compile a version that will work on the Brazilian APC UPS?

### ISSUE THREAD

**Issue by moraesgyn** [korylprince/hassio-apcupsd#22]
Hello!

there is a Brazilian that made a version compatible with the Brazilian APC UPS, its on sourceforge, I believe its has to be compiled for hassio, but I have no ideia on how to compile and make available on a repository, can you help me out please??

here is the source for the apcctrl ( same apcupsd, for Brazilians )

https://sourceforge.net/p/apcctrl/git/ci/master/tree/

thanks in advance,

Tony

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
