### ISSUE TITLE
Unknown values on some parameters

### ISSUE THREAD

**Issue by Alessandro1981** [korylprince/hassio-apcupsd#23]
I used the add on since a long time with hassio, updating to 104.1 I started to get some "unknown" for parameters that were correctly used in the past. 

These are the parameters I am getting back from add-on:
- sensor.ups_battery | unknown 
- sensor.ups_battery_shutdown | 5 
- sensor.ups_battery_timeout | 0 
- sensor.ups_cable_type | USB Cable 
- sensor.ups_daemon_info | 3.14.14 (31 May 2016) unknown 
- sensor.ups_driver | USB UPS Driver 
- sensor.ups_hostname | a722577e-apcupsd.local.hass.io 
- sensor.ups_input_voltage | unknown 
- sensor.ups_input_voltage_high | unknown 
- sensor.ups_input_voltage_low | unknown 
- sensor.ups_load | unknown 
- sensor.ups_mode | Stand Alone 
- sensor.ups_model | unknown 
- sensor.ups_name | APC UPS 
- sensor.ups_output_voltage | unknown 
- sensor.ups_shutdown_time | 3 
- sensor.ups_startup_time | 2020-09-17 16:31:45 +0200 
- sensor.ups_status | COMMLOST 
- sensor.ups_status_data | 001,018,0465 
- sensor.ups_status_date | 2020-09-17 16:31:55 +0200 
- sensor.ups_time_left | unknown 

Currently i am running Hassio 104.4 with addon version 1.9

**Comment by tboyce021** [comment]
I'm similarly getting `unknown` for `input_voltage_high`, `input_voltage_low`, and `output_voltage` but I do get correct values for everything else, including `battery`, `load`, `model`, and `time_left`.

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
