### ISSUE TITLE
Setup failed for apcupsd: Integration failed to initialize.

### ISSUE THREAD

**Issue by iondarie** [korylprince/hassio-apcupsd#24]
I am trying to install the addon but whenever I try to start it I get:

Log Details (ERROR)

Logger: homeassistant.setup
Source: setup.py:138 
First occurred: 22:16:53 (1 occurrences) 
Last logged: 22:16:53

Setup failed for apcupsd: Integration failed to initialize.

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
