### ISSUE TITLE
Hassbian instead of Hass.io

### ISSUE THREAD

**Issue by OldCurmudgeon3DP** [korylprince/hassio-apcupsd#26]
Is there a way to get this code installed under hassbian? I have a stable setup that's working and don't really want to rock the boat jumping several major revisions and a whole different flavor of HA.

What I'm hoping is to just get monitoring of an apcupsd install on another PC on the network. I already have NUT configured for the UPS attached to the Pi running HA.

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
