### ISSUE TITLE
Cannot connect to UPS from apcupsd

### ISSUE THREAD

**Issue by Sinbad95** [korylprince/hassio-apcupsd#28]
Hello,

I am trying to get my home-assistant to connect to my APC UPS device. The log for the add-on shows the following;
![image](https://user-images.githubusercontent.com/73907443/100389465-5735d100-3025-11eb-9d7f-cda619fd9459.png)

My config in the add-on is;
![image](https://user-images.githubusercontent.com/73907443/100389495-6ae13780-3025-11eb-9f61-a2e4355a7ec5.png)

And the config added to my configuration.yaml file is;
![image](https://user-images.githubusercontent.com/73907443/100389936-c3650480-3026-11eb-92ad-2cb07b504e8e.png)

I have home-assistant running on a virtual debian desktop that is hosted on my Windows10 PC, which has the UPS devices connected. Model of the UPS is APC Back-UPS XS 700U. On the Windows PC I have apcupsd installed with the default configurations and it is successfully seeing all the fields from the UPS device. I have tried setting the type to modbus in the config as suggested in one of the closed issues, but that made no difference.

running apcaccess on my Windows 10 PC, pointing to my home-assistant I get a subset of data (same as from within home assistant itself.

Does anyone have a solution for this issue?  Thanks

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
