### ISSUE TITLE
"device "/dev/usb/": no such file or directory"

### ISSUE THREAD

**Issue by coinfaslab** [korylprince/hassio-apcupsd#29]
Hi,
I get this error message when I start the daemon:
20-12-08 16:42:29 ERROR (SyncWorker_3) [supervisor.docker] Can't start addon_a722577e_apcupsd: 500 Server Error for http + docker: //localhost/v1.40/containers/b5117850db35526713f5fba56079da65a4c76be9arte90c5c597 Internal Error ("error gathering device information while adding custom device" / dev / usb / ": no such file or directory")
I would like to use this daemon because it is very interesting and has commands that solve my problems
Thanks

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
