### ISSUE TITLE
Multiple UPS devices

### ISSUE THREAD

**Issue by bonelessc** [korylprince/hassio-apcupsd#3]
As mentioned on the HASS.IO forums, would love to see the possibility to connect/monitor multiple UPS devices using the Ethernet option.

**Comment by korylprince** [comment]
@bonelessc I'm sorry for not getting to this a lot sooner. I haven't had a lot of time to work on this stuff.

With version 1.6 I've released a network-only version of the add-on. Refresh the repository in Hass.io and you should see the second add-on. Please let me know if you have any issues with it.

This allows you to use two UPSs at once: a USB one and a network one (just make sure to run them on different ports!)

At this point I think it's safe to say I'm not going to have the time to implement being able to add multiple UPSs in the add-on itself. I'd gladly accept a PR with that feature, but it's not something I'm going to implement myself. Therefore, I'm going to go ahead and close this issue.
