### ISSUE TITLE
Lost communications with UPS

### ISSUE THREAD

**Issue by monpelaud** [korylprince/hassio-apcupsd#5]
Hi,
Lost communications with UPS.
All worked fine with older Home Assitant versions.

My configuration:
resinos-hassio-1.3-raspberrypi3.img
Home Assistant 0.69.1

APC UPS Daemon log:
starting version 3.2.4
May 26 21:47:55 a722577e-apcupsd syslog.info syslogd started: BusyBox v1.27.2
May 26 19:47:55 a722577e-apcupsd daemon.notice apcupsd[9]: apcupsd 3.14.14 (31 May 2016) unknown startup succeeded
May 26 19:47:55 a722577e-apcupsd daemon.info apcupsd[9]: NIS server startup succeeded
May 26 19:49:05 a722577e-apcupsd daemon.warn apcupsd[9]: Communications with UPS lost.

Many thanks for your help

**Comment by korylprince** [comment]
Hello, are you still having these issues?

Have you tried restarting the add-on or the raspberry pi? Can you verify the USB is still plugged in?

**Comment by monpelaud** [comment]
Hello,
Thank you for your reply.
I restarted the add-on, restarted the raspberry and this issue is not solved.
I installed the add-on on a fresh hassio image without more success.
I restarted my ups, I changed the USB port with no more success.

Many thanks for your help

**Comment by korylprince** [comment]
To help further, you'll need to turn on [SSH debugging](https://developers.home-assistant.io/docs/en/hassio_debugging.html).

SSH into the OS and post the output of the following commands:

* `ls /dev/usb`
* `cat /sys/bus/usb/devices/*/product`

Also post your add-on config.

**Comment by monpelaud** [comment]
ls /dev/usb
hiddev0  hiddev1

cat /sys/bus/usb/devices/*/product
USB Keyboard
USB Optical Mouse
Back-UPS ES 700G FW:871.O2 .I USB FW:O2
DWC OTG Controller

add-on config
{
  "name": "APC UPS",
  "cable": "usb",
  "type": "usb",
  "device": "",
  "extra": []
}

**Comment by korylprince** [comment]
The issue might be with having two hiddev devices.

Try unplugging the keyboard, mouse, and UPS, then plug back in just the UPS after a few seconds.

Then restart the add-on and see if it works.

If not, then please post the output of:

`cat /sys/bus/usb/devices/*/uevent`

**Comment by monpelaud** [comment]
Hello,
Thanks a lot for your help and your quick replies.

Without keyboard and mouse all works fine.

Is there a way to specify the usb device used by my UPS?
May be by specify the usb device in the add-on config?
Something like:
"device":"/dev/usb/hiddev0",

Best regards

**Comment by monpelaud** [comment]
Now all works fine.

**Comment by korylprince** [comment]
This is partly due to [this issue](https://github.com/home-assistant/hassio/issues/331).

However, in this case I've just released version 1.5 which just passes all `/dev/usb` device instead of just `/dev/usb/hiddev0`. apcupsd **should** be able to detect which hiddev device is your UPS automatically now, even if your UPS isn't `hiddev0`.
