### ISSUE TITLE
After powercut sensors not updating

### ISSUE THREAD

**Issue by jchasey** [korylprince/hassio-apcupsd#6]
Had a powercut yesterday for about 30 mins and everything worked as expected with the sensors updating when the UPS kicked in etc. However once power was restored the sensors did not update and so are still showing 'SHUTTING DOWN' for status, although the battery correctly shows it is now back to 100% etc. It could simply be that the change in status was missed somehow? Possibly need to force a refresh of the sensors? If so how could that be done?

**Comment by korylprince** [comment]
Hello, sorry for a lack of response. Unfortunately I've not had much time to keep up with my Hass.io addons.

I'm afraid I don't have a good answer for this. I've had several outages and everything updates how I'd expect.

I do have some things you could check. First, make sure this wasn't just a one time fluke. If it happens consistently, then you need to see if it's apcupsd or Home Assistant that's not updating properly.

You'll need to install the apcaccess utility on your computer or use SSH, Portainer, etc to get a shell of the add-on.

You'd use `apcaccess -h <your hass.io IP>`. If that command spits out the wrong info, then apcupsd is not updating for some reason. Just restart the add-on in that case.

If it looks correct and Home Assistant still has the wrong info, then Home Assistant is not updating it's info for some reason. I'm pretty sure this is polled, so you may need to wait a few seconds to make sure it's actually pulled the latest information. Also check the Home Assistant log for any issues.

To "fix" this, you could first try restarting the add-on, but it's likely you'll need to restart Home Assistant to get it to pull the new data.

I'm sorry it took so long to answer, and I couldn't be of more help, but that's all I can think of.
