### ISSUE TITLE
Need ethernet version: Cannot start on hassio running on Docker on a virtualized Ubuntu Server. (No "/dev/usb/")

### ISSUE THREAD

**Issue by genestealer** [korylprince/hassio-apcupsd#7]
**Issue**
Cannot start on hassio running on Docker on a virtualized Ubuntu Server. (No USB)

**Detail**
Add-in fails to start in hass. At first this was due to the port already being in use. See issue: https://github.com/home-assistant/hassio/issues/689
Since removing the other server I tried starting starting again from hass, but with no luck. I then tried from Docker Portainer by manually starting the apcupsd Hass.io add-on which then presented me with the error.
My Home Assistant is in the form of Hass.IO in Docker on a virtualized Ubuntu Server 18.04, as per these instructions: https://bonani.tech/how-to-install-hass.io-on-ubuntu-server-18.04/ .

I'm connecting to the UPS via ethernet.

**My Config**

```
{
  "name": "APC UPS",
  "cable": "ether",
  "type": "snmp",
  "device": "192.168.1.60:161:APC:private",
  "extra": []
}

```

**HASS.IO error message before removing other server:**
`18-09-09 19:21:11 ERROR (SyncWorker_3) [hassio.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a722577e_apcupsd (77b4e8f39e7d0e20f99dc3f9e8b611fc5c13e354d74d94e445ea15d9fb120e03): Error starting userland proxy: listen tcp 0.0.0.0:3551: bind: address already in use")
`

**HASS.IO error message after removing other server:**
`18-09-09 19:27:55 ERROR (SyncWorker_0) [hassio.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/usb/": no such file or directory")`

FYI, this is the hardware as Hass.io sees:
```
serial:
/dev/ttyS4
/dev/ttyS7
/dev/ttyS8
/dev/ttyS11
/dev/ttyS24
/dev/ttyS21
/dev/ttyS31
/dev/ttyS18
/dev/ttyS6
/dev/ttyS1
/dev/ttyS22
/dev/ttyS10
/dev/ttyS20
/dev/ttyS19
/dev/ttyS29
/dev/ttyS2
/dev/ttyS17
/dev/ttyS3
/dev/ttyS16
/dev/ttyS27
/dev/ttyS25
/dev/ttyS13
/dev/ttyS14
/dev/ttyS15
/dev/ttyS28
/dev/ttyS23
/dev/ttyS30
/dev/ttyS26
/dev/ttyS5
/dev/ttyS12
/dev/ttyS9
/dev/ttyS0
input:
AT Translated Set 2 keyboard
Microsoft Vmbus HID-compliant Mouse
disk:
/dev/sda2
/dev/sda
/dev/sda3
/dev/sda1
gpio:
audio:
```

@korylprince sorry for all the edits.

**Comment by genestealer** [comment]
FYI, this is the hardware as Hass.io sees:
```
serial:
/dev/ttyS4
/dev/ttyS7
/dev/ttyS8
/dev/ttyS11
/dev/ttyS24
/dev/ttyS21
/dev/ttyS31
/dev/ttyS18
/dev/ttyS6
/dev/ttyS1
/dev/ttyS22
/dev/ttyS10
/dev/ttyS20
/dev/ttyS19
/dev/ttyS29
/dev/ttyS2
/dev/ttyS17
/dev/ttyS3
/dev/ttyS16
/dev/ttyS27
/dev/ttyS25
/dev/ttyS13
/dev/ttyS14
/dev/ttyS15
/dev/ttyS28
/dev/ttyS23
/dev/ttyS30
/dev/ttyS26
/dev/ttyS5
/dev/ttyS12
/dev/ttyS9
/dev/ttyS0
input:
AT Translated Set 2 keyboard
Microsoft Vmbus HID-compliant Mouse
disk:
/dev/sda2
/dev/sda
/dev/sda3
/dev/sda1
gpio:
audio:
```

**Comment by genestealer** [comment]
@korylprince Any chance you can let me know how best to fix this, I have tried forking and editing it myself but I couldn't get it to work.

**Comment by korylprince** [comment]
I'm sorry for the lack of response on this. I've not been able to keep up with this like I'd like.

I've released a second version of the add-on that doesn't require the `/dev/usb` path to exist. 

Reload the repository in Hass.io and you'll see the second add-on. If you have trouble with it working with your network UPS, please reply to this issue.

**Comment by genestealer** [comment]
Many thanks, can't wait to try it.

Update: I have been using this with my Ethernet ups for two years without issue.

**Comment by sblantipodi** [comment]
is this related? #14

**Comment by jmreicha** [comment]
I just ran into this error myself, haven't found a fix yet.

I followed the instructions from the readme and added the url to the git repo, installed the add-on, pointed it to my serial device and when I start it I don't see anything in the logs tab of th add-on. Looking at the supervisor logs I see,

```
20-06-04 13:24:42 ERROR (SyncWorker_9) [supervisor.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/usb/": no such file or directory")
20-06-04 13:26:12 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_a722577e_apcupsd application
20-06-04 13:26:12 ERROR (SyncWorker_4) [supervisor.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/usb/": no such file or directory")
20-06-04 13:42:56 INFO (SyncWorker_6) [supervisor.docker.interface] Clean addon_a722577e_apcupsd application
20-06-04 13:42:57 ERROR (SyncWorker_6) [supervisor.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/usb/": no such file or directory")
```

This is inside a VM running on Proxmox, which doesn't seem to map /dev/usb/ anywhere. For reference here is what HA tells me it sees.

![image](https://user-images.githubusercontent.com/1039098/83765252-8fdd8a80-a640-11ea-86cb-8abfe491f0b9.png)

**Comment by jmreicha** [comment]
More reading has led me here: https://community.home-assistant.io/t/new-apcupsd-hass-io-add-on/35149/79. Basically, make a udev mapping, still figuring how to do that.
