### ISSUE TITLE
Problem on out of battery

### ISSUE THREAD

**Issue by hugodelaroza** [korylprince/hassio-apcupsd#9]
Hi, I have the following problem: when I loose AC, my hassio senses it on the system, so after a long time, the battery goes into critical level, and then the system (a raspi 3) shuts down. In a very short time, AC returns, and UPS is still in critical level, so the battery starts chargin again and everything is ok, except that my raspi doesnt starts again because it never really loses AC

I want to program my hassio in a way that it remains online untill battery is out, so when AC returns, it is really off and boots again.

I hear another solution too.....

Thanks!!

**Comment by korylprince** [comment]
You'll need to replace the default scripts that cause a shutdown on low battery.

Check out the [Host Control](https://github.com/korylprince/hassio-apcupsd/tree/master/apcupsd#host-control) and [Tips & Tricks](https://github.com/korylprince/hassio-apcupsd/tree/master/apcupsd#tips--tricks) sections for info on how to do that.
